const router = require('express').Router()
const ctrl = require('../../controllers/account/dashboard.controller')

router.get('/overview',             ctrl.getOverview)
router.get('/stats',                ctrl.getStats)
router.get('/invoice-stats',        ctrl.getInvoiceStats)
router.get('/delivery-finance',     ctrl.getDeliveryFinance)
router.get('/order-vs-plant-costs', ctrl.getOrderVsPlantCosts)
router.get('/alerts',               ctrl.getFinancialAlerts)
router.get('/top-carriers',         ctrl.getTopCarriers)
router.get('/top-vendors',         ctrl.getTopVendors)
router.get('/project-budget-vs-actual', ctrl.getProjectBudgetVsActual)
router.get('/income-vs-expense',    ctrl.getIncomeVsExpense)
router.get('/recent-transactions',  ctrl.getRecentTransactions)
router.get('/upcoming-payments',    ctrl.getUpcomingPayments)
router.get('/payment-distribution', ctrl.getPaymentDistribution)
router.get('/revenue-trend',        ctrl.getRevenueTrend)
router.get('/expense-trend',        ctrl.getExpenseTrend)
router.get('/cost-breakdown',       ctrl.getCostBreakdown)
router.get('/wip-projects',         ctrl.getWipProjects)

module.exports = router
